Added tests and Travis integration. Moved form to new file 'forms.py'…
nexto/django-model-audit-history pull request #2
Opened 2019-01-24 14:53 UTC by Killsoft1692

…. Updated model field

2019-01-25 10:25 UTC, hheimbuerger requested changes
Please have a look at the three comments I left below (we mostly already discussed this in our call).

2019-01-25 10:25 UTC, hheimbuerger commented on audit_history/widgets.py
>              return mark_safe('<table>' + ''.join(rows) + '</table>')
As mentioned earlier in the call, this could be turned into a real template probably. Then we wouldn't need to concat the `<table>` here and you could roll in that `HISTORY_FIELD_VIEW` as well.

2019-01-25 10:25 UTC, hheimbuerger commented on audit_history/tests/main.py
> +        self.admin_add_url = '/admin/test_app/blogpost/add/'
Instead of hardcoding these URLs, how about [reversing them](https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#reversing-admin-urls)?

2019-01-25 10:25 UTC, hheimbuerger commented on audit_history/tests/test_audit_history_admin.py
> +                                  "position": self.blog_position,
The styleguide of the main project (which you haven't seen yet, I know), says that Python string literals should always use single quotes.

2019-01-25 15:16 UTC, Killsoft1692 commented on audit_history/tests/main.py
> +        self.admin_add_url = '/admin/test_app/blogpost/add/'
Done

2019-01-25 15:16 UTC, Killsoft1692 commented on audit_history/tests/test_audit_history_admin.py
> +                                  "position": self.blog_position,
Done

2019-01-25 16:36 UTC, Killsoft1692 commented on audit_history/widgets.py
>              return mark_safe('<table>' + ''.join(rows) + '</table>')
Done, please check: https://github.com/nexto/django-model-audit-history/commit/508b2269228bb10a740389560765e4ab26f365dc

2019-01-28 10:43 UTC, hheimbuerger commented on audit_history/widgets.py
>              return mark_safe('<table>' + ''.join(rows) + '</table>')
@Killsoft1692 Great, I think that is much cleaner, more readable and more extensible!

2019-01-28 10:45 UTC, hheimbuerger approved these changes

2019-01-28 10:46 UTC, merged